services:
  - type: web
    name: my-rails-app
    env: docker
    repo: https://github.com/878is878/WithTODO
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: bundle install && yarn install
    startCommand: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
      - key: MYSQL_PASSWORD
        value: password
      - key: TZ
        value: "Asia/Tokyo"
